import { useCallback, useEffect, useMemo, useState } from 'react'
import type { Session } from '@supabase/supabase-js'
import { defaultShifts } from './data'
import { isTestCleaningDay, schoolRepository, type PlanOptions, type Profile } from './schoolRepository'
import { isSupabaseConfigured } from './supabase'
import type { Attendance, Frequency, Task } from './types'

type Section = 'Dnes' | 'Úklid' | 'Docházka' | 'Kalendář' | 'Zásoby' | 'Praní' | 'Závady' | 'Nastavení'
const sections: Section[] = ['Dnes', 'Úklid', 'Docházka', 'Kalendář', 'Zásoby', 'Praní', 'Závady', 'Nastavení']
const icon: Record<Section, string> = { Dnes: '☀', Úklid: '✓', Docházka: '◷', Kalendář: '▣', Zásoby: '▤', Praní: '♨', Závady: '⚠', Nastavení: '⚙' }
const frequencies: Frequency[] = ['denně', 'týdně', '1–2× týdně', 'měsíčně', 'mimořádně']
const weekdays = ['Po', 'Út', 'St', 'Čt', 'Pá', 'So', 'Ne']
const todayLabel = new Intl.DateTimeFormat('cs-CZ', { weekday: 'long', day: 'numeric', month: 'long' }).format(new Date())

export default function App() {
  const [session, setSession] = useState<Session | null>(null); const [profile, setProfile] = useState<Profile | null>(null)
  const [tasks, setTasks] = useState<Task[]>([]); const [hasWorkPart, setHasWorkPart] = useState(false); const [attendance, setAttendance] = useState<Attendance[]>([])
  const [section, setSection] = useState<Section>('Dnes'); const [notice, setNotice] = useState(''); const [planOptions, setPlanOptions] = useState<PlanOptions>({ rooms: [], workParts: [] })
  const [editing, setEditing] = useState<Task | null>(null)
  const hours = useMemo(() => attendance.filter(item => item.end).reduce((sum, item) => sum + (new Date(item.end!).getTime() - new Date(item.start).getTime()) / 36e5, 0), [attendance])
  const load = useCallback(async (current: Session, knownProfile?: Profile | null) => {
    const activeProfile = knownProfile ?? await schoolRepository.profile(current.user.id)
    if (!activeProfile?.active) { setNotice('Účet není aktivní. Obraťte se na správce.'); return }
    setProfile(activeProfile)
    const [taskLoad, nextAttendance] = await Promise.all([schoolRepository.tasks(activeProfile), schoolRepository.attendance(activeProfile.id)])
    setTasks(taskLoad.tasks); setHasWorkPart(taskLoad.hasWorkPart); setAttendance(nextAttendance)
    if (activeProfile.role === 'caretaker') setPlanOptions(await schoolRepository.planOptions())
  }, [])
  useEffect(() => { if (!isSupabaseConfigured) return; schoolRepository.getSession().then(next => { setSession(next); if (next) load(next).catch(error => setNotice(error.message)) }); const { data } = schoolRepository.onAuthChange(next => { setSession(next); setProfile(null); setTasks([]); setHasWorkPart(false); setAttendance([]); if (next) load(next).catch(error => setNotice(error.message)) }); return () => data.subscription.unsubscribe() }, [load])
  useEffect(() => { if (!session || !profile) return; const channel = schoolRepository.subscribe(() => load(session, profile).catch(error => setNotice(error.message))); return () => { channel.unsubscribe() } }, [session, profile, load])
  if (!isSupabaseConfigured) return <SetupScreen />
  if (!session || !profile) return <LoginScreen notice={notice} onLoginWithGoogle={async () => { try { setNotice(''); await schoolRepository.signInWithGoogle() } catch (error) { setNotice(error instanceof Error ? error.message : 'Přihlášení přes Google se nezdařilo.') } }} />
  const complete = async (id: string) => { const target = tasks.find(task => task.id === id); if (!target || !target.canComplete) return; if (target.prerequisite && !tasks.find(task => task.id === target.prerequisite)?.done) { setNotice('Nejdříve je potřeba zamést nebo vysát.'); return } try { setNotice(''); await schoolRepository.setCompletion(id, profile.id, !target.done); await load(session, profile) } catch (error) { setNotice(error instanceof Error ? error.message : 'Úkol se nepodařilo uložit.') } }
  const clock = async () => { const open = attendance.find(item => !item.end); try { setNotice(''); if (open?.id) await schoolRepository.finishAttendance(open.id); else await schoolRepository.startAttendance(profile.id); await load(session, profile) } catch (error) { setNotice(error instanceof Error ? error.message : 'Docházku se nepodařilo uložit.') } }
  const saveTask = async (task: Task) => { try { setNotice(''); await schoolRepository.saveTask(task); setEditing(null); await load(session, profile) } catch (error) { setNotice(error instanceof Error ? error.message : 'Plán se nepodařilo uložit.') } }
  const openShift = attendance.find(item => !item.end); const visible = section === 'Dnes' ? tasks.filter(task => task.active && task.dueToday) : tasks
  return <main className="app"><header><div><p className="eyebrow">ÚKLID ŠKOLY · ŠKOLA</p><h1>{section}</h1><p className="date">{todayLabel}</p></div><button className="avatar" aria-label="Odhlásit" title="Odhlásit" onClick={() => schoolRepository.signOut()}>{profile.full_name[0]}</button></header>{notice && <div className="notice">{notice}</div>}
    {section === 'Dnes' && <><section className="hero"><span>{isTestCleaningDay ? 'Testovací zobrazení pondělního úklidového dne.' : [1, 3, 5].includes(new Date().getDay()) ? 'Dnes je standardní úklidový den.' : 'Dnes není pravidelný úklidový den.'}</span><strong>{visible.filter(task => task.done).length} / {visible.length} hotovo</strong></section>{profile.role === 'cleaner' && !hasWorkPart && <section className="empty assignment-empty"><span>⚙</span><h2>Nemáte zatím přiřazenou pracovní část.</h2><p>Správce vám musí přiřadit část A nebo B. Google jméno se pro oprávnění nepoužívá.</p></section>}{(profile.role === 'caretaker' || hasWorkPart) && <TaskHierarchy tasks={visible} onComplete={complete} />}</>}
    {section === 'Úklid' && <>{profile.role === 'caretaker' ? <PlanManager tasks={tasks} options={planOptions} editing={editing} onEdit={setEditing} onCancel={() => setEditing(null)} onSave={saveTask} /> : <><div className="filters">{frequencies.map(frequency => <span key={frequency}>{frequency}</span>)}</div><TaskHierarchy tasks={visible.filter(task => task.active)} onComplete={complete} /></>}</>}
    {section === 'Docházka' && <section className="panel"><div className="timecard"><small>{openShift ? 'Směna probíhá' : 'Připraveno k evidenci'}</small><strong>{profile.full_name}</strong><button onClick={clock}>{openShift ? 'Ukončit směnu' : 'Začít směnu'}</button></div><div className="summary"><span>Dnes <b>{attendance.filter(item => item.date === new Date().toISOString().slice(0, 10)).length} směna</b></span><span>Měsíc <b>{hours.toFixed(1)} h</b></span></div><p className="hint">Docházka se ukládá do sdílené databáze. Praní se do pracovní doby nezapočítává.</p></section>}
    {section === 'Kalendář' && <Placeholder title="Plán úklidu" text="Připraveno pro budoucí propojení sdíleného Google Kalendáře a kontrolu kolizí školních akcí." />}{section === 'Zásoby' && <Placeholder title="Zásoby" text="Datový model zásob je připraven. Správu zásob doplníme v další fázi." />}{section === 'Praní' && <Placeholder title="Praní" text="Datový model praní je samostatný a nezapočítává se do docházky." />}{section === 'Závady' && <Placeholder title="Závady" text="Datový model závad a budoucích fotografií je připraven." />}
    {section === 'Nastavení' && <section className="panel"><h2>Budovy a výchozí směny</h2><div className="building"><b>Škola</b><span>aktivní budova</span></div><div className="building muted"><b>Školka</b><span>připravena k přidání</span></div>{defaultShifts.map(shift => <div className="shift" key={shift.worker}><span>{shift.worker}</span><span>{shift.start}–{shift.end}</span></div>)}<p className="hint">Přihlášen: {profile.full_name} · {profile.role === 'caretaker' ? 'správce' : 'uklízečka'}</p></section>}
    <nav>{sections.map(item => <button key={item} className={section === item ? 'active' : ''} onClick={() => setSection(item)}><i>{icon[item]}</i><span>{item}</span></button>)}</nav></main>
}

function TaskHierarchy({ tasks, onComplete }: { tasks: Task[]; onComplete: (id: string) => void }) {
  const common = tasks.filter(task => !task.roomId); const floorGroups = new Map<string, Task[]>()
  tasks.filter(task => task.roomId).forEach(task => floorGroups.set(`${task.building}|${task.floor}`, [...(floorGroups.get(`${task.building}|${task.floor}`) ?? []), task]))
  return <>{common.length > 0 && <section className="shared-tasks"><h2>Společné úkoly</h2><TaskRows tasks={common} onComplete={onComplete} /></section>}{[...floorGroups.entries()].sort(([, a], [, b]) => a[0].floorSort - b[0].floorSort).map(([key, floorTasks]) => <FloorGroup key={key} label={key.split('|')[1]} tasks={floorTasks} onComplete={onComplete} />)}{tasks.length === 0 && <section className="empty"><span>✓</span><h2>Pro tento den nejsou naplánované úkoly.</h2></section>}</>
}
function FloorGroup({ label, tasks, onComplete }: { label: string; tasks: Task[]; onComplete: (id: string) => void }) {
  const [open, setOpen] = useState(true); const rooms = new Map<string, Task[]>()
  tasks.forEach(task => rooms.set(task.room, [...(rooms.get(task.room) ?? []), task]))
  const complete = tasks.filter(task => task.done).length
  return <section className="floor-group"><button className="floor-toggle" onClick={() => setOpen(!open)} aria-expanded={open}><span><b>{label}</b><small>{complete} / {tasks.length} hotovo</small></span><i>{open ? '⌃' : '⌄'}</i></button>{open && <div className="room-list">{[...rooms.entries()].map(([room, roomTasks]) => <section className="room-group" key={room}><h3>{room}</h3><TaskRows tasks={roomTasks} onComplete={onComplete} /></section>)}</div>}</section>
}
function TaskRows({ tasks, onComplete }: { tasks: Task[]; onComplete: (id: string) => void }) { return <div className="tasks">{[...tasks].sort((a, b) => a.sortOrder - b.sortOrder).map(task => <article className={task.done ? 'task done' : 'task'} key={task.id}><button className="check" disabled={!task.canComplete} onClick={() => onComplete(task.id)} aria-label={`Označit ${task.title} hotovo`}>{task.done ? '✓' : ''}</button><div><h4>{task.title}</h4><p>{task.assignedTo}{task.prerequisite ? ' · nejdříve zamést / vysát' : ''}</p></div></article>)}</div> }

function PlanManager({ tasks, options, editing, onEdit, onCancel, onSave }: { tasks: Task[]; options: PlanOptions; editing: Task | null; onEdit: (task: Task) => void; onCancel: () => void; onSave: (task: Task) => Promise<void> }) {
  const addTask = () => onEdit({ id: '', room: 'Společný úkol', floor: 'Společné úkoly', floorSort: -1, building: 'Škola', title: '', frequency: 'denně', assignedTo: 'nepřiřazeno', done: false, dueToday: false, sortOrder: 10, scheduleDays: [1, 3, 5], monthlyDay: null, workPartId: null, assignmentMode: 'fixed', rotationAnchorDate: null, rotationIntervalWeeks: 1, active: true })
  return <section className="plan-manager"><p className="hint">Správce může přidat nebo upravit plán. Deaktivovaný úkol zůstane v historii, ale nezobrazí se pracovníkům.</p>{editing ? <TaskEditor task={editing} options={options} onCancel={onCancel} onSave={onSave} /> : <><button className="add-task" onClick={addTask}>+ Nový úkol</button><div className="plan-list">{[...tasks].sort((a, b) => a.floorSort - b.floorSort || a.room.localeCompare(b.room, 'cs') || a.sortOrder - b.sortOrder).map(task => <button key={task.id} className="plan-row" onClick={() => onEdit({ ...task })}><span><b>{task.floor} · {task.room}</b><small>{task.title} · {task.frequency}{task.active ? '' : ' · neaktivní'}</small></span><i>Upravit</i></button>)}</div></>}</section>
}
function TaskEditor({ task, options, onCancel, onSave }: { task: Task; options: PlanOptions; onCancel: () => void; onSave: (task: Task) => Promise<void> }) {
  const [draft, setDraft] = useState(task); const update = <K extends keyof Task>(key: K, value: Task[K]) => setDraft(current => ({ ...current, [key]: value }))
  const setRoom = (id: string) => { const room = options.rooms.find(item => item.id === id); setDraft(current => ({ ...current, roomId: id || undefined, room: room?.name ?? 'Společný úkol', floor: room?.floor ?? 'Společné úkoly', floorSort: room?.floorSort ?? -1, building: room?.building ?? 'Škola' })) }
  const toggleDay = (day: number) => update('scheduleDays', draft.scheduleDays.includes(day) ? draft.scheduleDays.filter(item => item !== day) : [...draft.scheduleDays, day].sort())
  return <form className="task-editor" onSubmit={event => { event.preventDefault(); void onSave(draft) }}><h2>Upravit úkol</h2><label>Činnost<input value={draft.title} onChange={event => update('title', event.target.value)} required /></label><label>Místnost / společný úkol<select value={draft.roomId ?? ''} onChange={event => setRoom(event.target.value)}><option value="">Společný úkol pro školu</option>{options.rooms.map(room => <option key={room.id} value={room.id}>{room.floor} · {room.name}</option>)}</select></label><label>Patro / sekce<input value={draft.floor} readOnly /></label><label>Frekvence<select value={draft.frequency} onChange={event => update('frequency', event.target.value as Frequency)}>{frequencies.map(item => <option key={item}>{item}</option>)}</select></label>{draft.frequency !== 'měsíčně' && draft.frequency !== 'mimořádně' && <fieldset><legend>Dny v týdnu</legend><div className="day-buttons">{weekdays.map((day, index) => <button type="button" className={draft.scheduleDays.includes(index + 1) ? 'selected' : ''} onClick={() => toggleDay(index + 1)} key={day}>{day}</button>)}</div></fieldset>}{draft.frequency === 'měsíčně' && <label>Den v měsíci<input type="number" min="1" max="31" value={draft.monthlyDay ?? 1} onChange={event => update('monthlyDay', Number(event.target.value))} /></label>}<label>Pracovní část<select value={draft.workPartId ?? ''} onChange={event => update('workPartId', event.target.value || null)}><option value="">Bez části A/B</option>{options.workParts.map(part => <option key={part.id} value={part.id}>{part.code} – {part.name}</option>)}</select></label><label>Typ přiřazení<select value={draft.assignmentMode} onChange={event => update('assignmentMode', event.target.value as 'fixed' | 'rotating')}><option value="fixed">Pevné / část A-B</option><option value="rotating">Střídání</option></select></label>{draft.assignmentMode === 'rotating' && <><label>Začátek střídání<input type="date" value={draft.rotationAnchorDate ?? ''} onChange={event => update('rotationAnchorDate', event.target.value || null)} /></label><label>Interval střídání (týdny)<input type="number" min="1" value={draft.rotationIntervalWeeks ?? 1} onChange={event => update('rotationIntervalWeeks', Number(event.target.value))} /></label></>}<label>Pořadí<input type="number" value={draft.sortOrder} onChange={event => update('sortOrder', Number(event.target.value))} /></label><label className="switch"><input type="checkbox" checked={draft.active} onChange={event => update('active', event.target.checked)} /> Aktivní úkol</label><div className="editor-actions"><button type="button" onClick={onCancel}>Zrušit</button><button type="submit">Uložit plán</button></div></form>
}
function Placeholder({ title, text }: { title: string; text: string }) { return <section className="empty"><span>○</span><h2>{title}</h2><p>{text}</p></section> }
function SetupScreen() { return <main className="app"><section className="empty"><span>⚙</span><h1>Dokončete propojení</h1><p>Do souboru <code>.env.local</code> vložte veřejnou adresu projektu Supabase a anon klíč podle <code>.env.example</code>. Poté aplikaci restartujte.</p></section></main> }
function LoginScreen({ notice, onLoginWithGoogle }: { notice: string; onLoginWithGoogle: () => Promise<void> }) { return <main className="app"><section className="panel login"><p className="eyebrow">ÚKLID ŠKOLY</p><h1>Přihlášení</h1><p className="hint">Přihlaste se školním účtem. Zobrazí se pouze data podle vašich oprávnění.</p>{notice && <div className="notice">{notice}</div>}<button type="button" onClick={() => void onLoginWithGoogle()}>Pokračovat přes Google</button></section></main> }
