create extension if not exists pgcrypto;
do $$ begin create type public.app_role as enum ('cleaner', 'caretaker'); exception when duplicate_object then null; end $$;
do $$ begin create type public.task_frequency as enum ('cleaning_day', 'weekly', 'once_or_twice_weekly', 'monthly', 'extraordinary'); exception when duplicate_object then null; end $$;
do $$ begin create type public.shift_status as enum ('planned', 'completed', 'cancelled'); exception when duplicate_object then null; end $$;
do $$ begin create type public.incident_status as enum ('reported', 'in_progress', 'resolved'); exception when duplicate_object then null; end $$;

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text not null, role public.app_role not null default 'cleaner', active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.buildings (id uuid primary key default gen_random_uuid(), name text not null unique, active boolean not null default true, created_at timestamptz not null default now());
create table public.floors (id uuid primary key default gen_random_uuid(), building_id uuid not null references public.buildings(id) on delete cascade, name text not null, sort_order integer not null default 0, unique(building_id,name));
create table public.rooms (id uuid primary key default gen_random_uuid(), building_id uuid not null references public.buildings(id) on delete cascade, floor_id uuid references public.floors(id) on delete set null, name text not null, active boolean not null default true, sort_order integer not null default 0, unique(building_id,name));
create table public.cleaning_tasks (id uuid primary key default gen_random_uuid(), room_id uuid references public.rooms(id) on delete set null, name text not null, frequency public.task_frequency not null, active boolean not null default true, sort_order integer not null default 0, requires_task_id uuid references public.cleaning_tasks(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.task_assignments (id uuid primary key default gen_random_uuid(), task_id uuid not null references public.cleaning_tasks(id) on delete cascade, worker_id uuid not null references public.profiles(id) on delete cascade, active boolean not null default true, unique(task_id,worker_id));
create table public.shifts (id uuid primary key default gen_random_uuid(), worker_id uuid not null references public.profiles(id), building_id uuid not null references public.buildings(id), shift_date date not null, planned_start time not null, planned_end time not null, status public.shift_status not null default 'planned', check(planned_end > planned_start));
create table public.attendance (id uuid primary key default gen_random_uuid(), worker_id uuid not null references public.profiles(id), building_id uuid not null references public.buildings(id), attendance_date date not null, started_at timestamptz not null default now(), ended_at timestamptz, note text, created_at timestamptz not null default now(), check(ended_at is null or ended_at >= started_at));
create table public.stock_items (id uuid primary key default gen_random_uuid(), name text not null unique, quantity numeric not null default 0 check(quantity >= 0), minimum_quantity numeric not null default 0 check(minimum_quantity >= 0), unit text not null default 'ks', active boolean not null default true, updated_at timestamptz not null default now());
create table public.laundry_records (id uuid primary key default gen_random_uuid(), laundry_date date not null default current_date, worker_id uuid not null references public.profiles(id), note text, created_at timestamptz not null default now());
create table public.incidents (id uuid primary key default gen_random_uuid(), incident_date date not null default current_date, worker_id uuid not null references public.profiles(id), building_id uuid not null references public.buildings(id), room_id uuid references public.rooms(id) on delete set null, description text not null, status public.incident_status not null default 'reported', photo_path text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.cleaning_completions (id uuid primary key default gen_random_uuid(), completion_date date not null default current_date, task_id uuid not null references public.cleaning_tasks(id) on delete cascade, worker_id uuid not null references public.profiles(id), completed boolean not null default true, completed_at timestamptz, unique(completion_date,task_id));
create index attendance_worker_date_idx on public.attendance(worker_id,attendance_date); create index completion_task_date_idx on public.cleaning_completions(task_id,completion_date); create index shifts_worker_date_idx on public.shifts(worker_id,shift_date);

create or replace function public.set_updated_at() returns trigger language plpgsql set search_path=public as $$ begin new.updated_at := now(); return new; end; $$;
create trigger set_profiles_updated_at before update on public.profiles for each row execute procedure public.set_updated_at();
create trigger set_tasks_updated_at before update on public.cleaning_tasks for each row execute procedure public.set_updated_at();
create trigger set_stock_updated_at before update on public.stock_items for each row execute procedure public.set_updated_at();
create trigger set_incidents_updated_at before update on public.incidents for each row execute procedure public.set_updated_at();
create or replace function public.is_caretaker() returns boolean language sql security definer set search_path=public stable as $$ select exists(select 1 from public.profiles where id=auth.uid() and role='caretaker' and active); $$;
create or replace function public.can_complete_task(target_task_id uuid) returns boolean language sql security definer set search_path=public stable as $$ select public.is_caretaker() or exists(select 1 from public.task_assignments ta where ta.task_id=target_task_id and ta.worker_id=auth.uid() and ta.active); $$;
revoke all on function public.is_caretaker() from public;
revoke all on function public.can_complete_task(uuid) from public;
grant execute on function public.is_caretaker() to authenticated;
grant execute on function public.can_complete_task(uuid) to authenticated;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,full_name,role) values(new.id,coalesce(new.raw_user_meta_data->>'full_name',split_part(new.email,'@',1)),'cleaner') on conflict(id) do nothing; return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create or replace function public.enforce_mopping_prerequisite() returns trigger language plpgsql security definer set search_path=public as $$ declare prerequisite uuid; begin if new.completed then select requires_task_id into prerequisite from public.cleaning_tasks where id=new.task_id; if prerequisite is not null and not exists(select 1 from public.cleaning_completions where task_id=prerequisite and completion_date=new.completion_date and completed) then raise exception 'Nejdříve je potřeba dokončit zametání nebo vysávání.'; end if; new.completed_at:=coalesce(new.completed_at,now()); else new.completed_at:=null; end if; return new; end; $$;
create trigger enforce_mopping_prerequisite before insert or update on public.cleaning_completions for each row execute procedure public.enforce_mopping_prerequisite();

alter table public.profiles enable row level security; alter table public.buildings enable row level security; alter table public.floors enable row level security; alter table public.rooms enable row level security; alter table public.cleaning_tasks enable row level security; alter table public.task_assignments enable row level security; alter table public.shifts enable row level security; alter table public.attendance enable row level security; alter table public.stock_items enable row level security; alter table public.laundry_records enable row level security; alter table public.incidents enable row level security; alter table public.cleaning_completions enable row level security;
grant usage on schema public to authenticated;
grant select on public.profiles, public.buildings, public.floors, public.rooms, public.cleaning_tasks, public.task_assignments, public.shifts, public.attendance, public.stock_items, public.laundry_records, public.incidents, public.cleaning_completions to authenticated;
grant insert, update, delete on public.profiles, public.buildings, public.floors, public.rooms, public.cleaning_tasks, public.task_assignments, public.shifts, public.attendance, public.stock_items, public.laundry_records, public.incidents, public.cleaning_completions to authenticated;
create policy "profiles own or caretaker" on public.profiles for select to authenticated using(id=auth.uid() or public.is_caretaker()); create policy "caretaker manages profiles" on public.profiles for all to authenticated using(public.is_caretaker()) with check(public.is_caretaker());
create policy "read buildings" on public.buildings for select to authenticated using(true); create policy "manage buildings" on public.buildings for all to authenticated using(public.is_caretaker()) with check(public.is_caretaker());
create policy "read floors" on public.floors for select to authenticated using(true); create policy "manage floors" on public.floors for all to authenticated using(public.is_caretaker()) with check(public.is_caretaker());
create policy "read rooms" on public.rooms for select to authenticated using(true); create policy "manage rooms" on public.rooms for all to authenticated using(public.is_caretaker()) with check(public.is_caretaker());
create policy "read tasks" on public.cleaning_tasks for select to authenticated using(active or public.is_caretaker()); create policy "manage tasks" on public.cleaning_tasks for all to authenticated using(public.is_caretaker()) with check(public.is_caretaker());
create policy "read own assignments" on public.task_assignments for select to authenticated using(worker_id=auth.uid() or public.is_caretaker()); create policy "manage assignments" on public.task_assignments for all to authenticated using(public.is_caretaker()) with check(public.is_caretaker());
create policy "read own shifts" on public.shifts for select to authenticated using(worker_id=auth.uid() or public.is_caretaker()); create policy "manage shifts" on public.shifts for all to authenticated using(public.is_caretaker()) with check(public.is_caretaker());
create policy "read own attendance" on public.attendance for select to authenticated using(worker_id=auth.uid() or public.is_caretaker()); create policy "start own attendance" on public.attendance for insert to authenticated with check(worker_id=auth.uid() or public.is_caretaker()); create policy "update own attendance" on public.attendance for update to authenticated using(worker_id=auth.uid() or public.is_caretaker()) with check(worker_id=auth.uid() or public.is_caretaker());
create policy "read stock" on public.stock_items for select to authenticated using(true); create policy "manage stock" on public.stock_items for all to authenticated using(public.is_caretaker()) with check(public.is_caretaker());
create policy "read own laundry" on public.laundry_records for select to authenticated using(worker_id=auth.uid() or public.is_caretaker()); create policy "create own laundry" on public.laundry_records for insert to authenticated with check(worker_id=auth.uid() or public.is_caretaker());
create policy "read incidents" on public.incidents for select to authenticated using(true); create policy "report own incident" on public.incidents for insert to authenticated with check(worker_id=auth.uid()); create policy "manage incidents" on public.incidents for all to authenticated using(public.is_caretaker()) with check(public.is_caretaker());
create policy "read completions" on public.cleaning_completions for select to authenticated using(true); create policy "complete assigned task" on public.cleaning_completions for insert to authenticated with check(worker_id=auth.uid() and public.can_complete_task(task_id)); create policy "change own completion" on public.cleaning_completions for update to authenticated using(worker_id=auth.uid() or public.is_caretaker()) with check((worker_id=auth.uid() and public.can_complete_task(task_id)) or public.is_caretaker());

insert into public.buildings(name) values('Škola'),('Školka') on conflict(name) do nothing;
insert into public.floors(building_id,name,sort_order) select b.id,v.name,v.sort_order from public.buildings b cross join(values('Přízemí',0),('1. patro',1),('2. patro',2),('3. patro',3),('4. patro',4),('Schodiště',5))v(name,sort_order) where b.name='Škola' on conflict(building_id,name) do nothing;
-- Konkrétní místnosti a jediný schválený plán úklidu seeduje navazující migrace 202608270002_cleaning_schedule.sql.
insert into public.rooms(building_id,floor_id,name,sort_order) select b.id,f.id,v.name,v.sort_order from public.buildings b join public.floors f on f.building_id=b.id join(values('Chodba – přízemí','Přízemí',1),('Třídy','1. patro',2),('Schodiště','Schodiště',4))v(name,floor_name,sort_order) on f.name=v.floor_name where b.name='Škola' on conflict(building_id,name) do nothing;
insert into public.stock_items(name,quantity,minimum_quantity,unit) values('Toaletní papír',0,10,'role'),('Tekuté mýdlo',0,2,'l'),('Houbičky',0,5,'ks'),('Hadry',0,10,'ks'),('Čisticí prostředky',0,2,'ks'),('Pytle do košů',0,2,'role'),('Prací prostředek',0,1,'ks'),('Dezinfekce',0,2,'l'),('Pytle do vysavačů',0,5,'ks') on conflict(name) do nothing;
do $$ begin alter publication supabase_realtime add table public.cleaning_completions; exception when duplicate_object then null; end $$; do $$ begin alter publication supabase_realtime add table public.attendance; exception when duplicate_object then null; end $$;
